# Generated by Django 5.1.3 on 2025-01-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.ManyToManyField(to='app.rating'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.ManyToManyField(to='app.rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
